<?php
/**
 * @file
 * Installation functions for httpbl.
 */

/**
 * Implementation of hook_schema().
 */
function httpbl_schema() {
  $schema['httpbl'] = array(
    'description' => t('Stores http:BL database cache.'),
    'fields' => array(
      'hostname' => array(
        'type' => 'varchar',
        'length' => '128',
        'not null' => TRUE,
        'description' => t('Primary key: Hostname (IP address)'),
      ),
      'status' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
        'description' => t('Cache status (HTTPBL_LIST_* constants)'),
      ),
      'expire' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'disp-width' => '11',
        'description' => t('A Unix timestamp indicating when the cache entry should expire.'),
      ),
    ),
    'primary key' => array('hostname'),
    'indexes' => array(
      'expire' => array('expire')
    ),
  );
  return $schema;
}


/**
 * Implementation of hook_uninstall().
 */
function httpbl_uninstall() {
  backdrop_uninstall_schema('httpbl');
}

/**
 * Move httpbl settings from variables to config.
 */
function httpbl_update_1000() {
  // Migrate variables to config.
  $config = config('httpbl.settings');
  $config->set('accesskey', update_variable_get('httpbl_accesskey', null));
  $config->set('check', update_variable_get('httpbl_check', 0));
  $config->set('footer', update_variable_get('httpbl_footer', FALSE));
  $config->set('link', update_variable_get('httpbl_link', null));
  $config->set('word', update_variable_get('httpbl_word', 'randomness'));
  $config->set('log', update_variable_get('httpbl_log', 1));
  $config->set('stats', update_variable_get('httpbl_stats', TRUE));
  $config->set('cache', update_variable_get('httpbl_cache', 1));
  $config->set('black_threshold', update_variable_get('httpbl_black_threshold', 50));
  $config->set('message_black', update_variable_get('httpbl_message_black', t('Sorry, your IP address (%ip) has been blacklisted by <a href="%ipurl">http:BL</a>.%honeypot')));
  $config->set('grey_threshold', update_variable_get('httpbl_grey_threshold', 1));
  $config->set('message_grey', update_variable_get('httpbl_message_grey', t('<p>We\'re sorry!<br /> We <strong>cannot</strong> let you access our website at this time.</p> <p>Your IP address (%ip) has been identified as a <em>possible</em> source of suspicious, robotic traffic and has been greylisted by <a href="%ipurl">Project Honeypot</a>.</p><p>If you are an actual human visitor who can read simple instructions,<br />you may try getting whitelisted on <a href="%whitelisturl">%whitelisturl</a>.</p>%honeypot')));
  $config->set('safe_offset', update_variable_get('httpbl_safe_offset', 10800));
  $config->set('greylist_offset', update_variable_get('httpbl_greylist_offset', 86400));
  $config->set('blacklist_offest', update_variable_get('httpbl_blacklist_offset', 31536000));
  $config->set('stat_comment', update_variable_get('httpbl_stat_comment', 0));
  $config->set('stat_black', update_variable_get('httpbl_stat_black', 0));
  $config->set('stat_grey', update_variable_get('httpbl_stat_grey', 0));
  $config->save();

  // Delete variables.
  update_variable_del('httpbl_accesskey');
  update_variable_del('httpbl_check');
  update_variable_del('httpbl_footer');
  update_variable_del('httpbl_link');
  update_variable_del('httpbl_word');
  update_variable_del('httpbl_log');
  update_variable_del('httpbl_stats');
  update_variable_del('httpbl_cache');
  update_variable_del('httpbl_black_threshold');
  update_variable_del('httpbl_message_black');
  update_variable_del('httpbl_grey_threshold');
  update_variable_del('httpbl_message_grey');
  update_variable_del('httpbl_safe_offset');
  update_variable_del('httpbl_greylist_offset');
  update_variable_del('httpbl_blacklist_offset');
  update_variable_del('httpbl_stat_comment');
  update_variable_del('httpbl_stat_black');
  update_variable_del('httpbl_stat_grey');
}

/**
 * Store statistics in state variables rather than config.
 */
function httpbl_update_1001() {
  $config = config('httpbl.settings');
  state_set('httpbl_stat_black', $config->get('stat_black'));
  $config->clear('stat_black');
  state_set('httpbl_stat_comment', $config->get('stat_comment'));
  $config->clear('stat_comment');
  state_set('httpbl_stat_grey', $config->get('stat_grey'));
  $config->clear('stat_grey');
  $config->save();
}

/**
 * Convert and add httpbl blocked hosts View.
 */
function httpbl_update_1002() {
  $view_config = [
    "_config_name" => "views.view.httpbl_blocked_hosts",
    "name" => "httpbl_blocked_hosts",
    "description" =>
        "Blocked Visitors via Honeypot.org.  This requires caching to be enabled at admin >> config >> people >> httpbl.",
    "tag" => "http:BL",
    "disabled" => FALSE,
    "base_table" => "httpbl",
    "human_name" => "http:BL Blocked Hosts",
    "core" => 0,
    "display" => [
        "default" => [
            "display_title" => "Defaults",
            "display_plugin" => "default",
            "display_options" => [
                "query" => [
                    "type" => "views_query",
                    "options" => ["query_comment" => FALSE],
                ],
                "title" => "http:BL Blocked Hosts",
                "use_more_always" => FALSE,
                "access" => ["type" => "perm", "perm" => "access site reports"],
                "cache" => ["type" => "none"],
                "exposed_form" => ["type" => "basic"],
                "pager" => [
                    "type" => "full",
                    "options" => [
                        "items_per_page" => "25",
                        "offset" => "0",
                        "id" => "0",
                    ],
                ],
                "style_plugin" => "table",
                "style_options" => [
                    "columns" => [
                        "counter" => "counter",
                        "hostname" => "hostname",
                        "status" => "status",
                        "expire" => "expire",
                    ],
                    "default" => "-1",
                    "info" => [
                        "counter" => ["align" => "", "separator" => ""],
                        "hostname" => [
                            "sortable" => 0,
                            "default_sort_order" => "asc",
                            "align" => "",
                            "separator" => "",
                        ],
                        "status" => [
                            "sortable" => 0,
                            "default_sort_order" => "asc",
                            "align" => "",
                            "separator" => "",
                        ],
                        "expire" => [
                            "sortable" => 0,
                            "default_sort_order" => "asc",
                            "align" => "",
                            "separator" => "",
                        ],
                    ],
                ],
                "header" => [
                    "text" => [
                        "id" => "text",
                        "table" => "views",
                        "field" => "area",
                        "empty" => TRUE,
                        "content" => "IP addresses blocked from access based on suspicious activity per Project Honeypot.

    		Status of 1 = Blacklisted IPs (also inserted as banned hosts in Blocked_IPs table)
    		Status of 2 = Greylisted IPs",
                        "format" => "plain_text",
                    ],
                ],
                "empty" => [
                    "text" => [
                        "id" => "text",
                        "table" => "views",
                        "field" => "area",
                        "empty" => TRUE,
                        "content" => "No blocked IPs at this time.",
                        "format" => "plain_text",
                    ],
                ],
                "fields" => [
                    "hostname" => [
                        "id" => "hostname",
                        "table" => "httpbl",
                        "field" => "hostname",
                        "alter" => [
                            "make_link" => TRUE,
                            "path" =>
                                "http://www.projecthoneypot.org/search_ip.php?ip=[hostname]",
                        ],
                        "hide_alter_empty" => FALSE,
                    ],
                    "status" => [
                        "id" => "status",
                        "table" => "httpbl",
                        "field" => "status",
                    ],
                    "expire" => [
                        "id" => "expire",
                        "table" => "httpbl",
                        "field" => "expire",
                        "hide_alter_empty" => FALSE,
                        "date_format" => "long",
                    ],
                ],
                "sorts" => [
                    "expire" => [
                        "id" => "expire",
                        "table" => "httpbl",
                        "field" => "expire",
                    ],
                ],
                "filters" => [
                    "status" => [
                        "id" => "status",
                        "table" => "httpbl",
                        "field" => "status",
                        "operator" => ">",
                        "value" => ["value" => "0"],
                        "expose" => ["operator" => FALSE],
                    ],
                ],
            ],
        ],
        "page_1" => [
            "display_title" => "Page",
            "display_plugin" => "page",
            "display_options" => [
                "query" => ["type" => "views_query", "options" => []],
                "defaults" => ["hide_admin_links" => FALSE],
                "path" => "admin/reports/blocked-hosts",
                "menu" => [
                    "type" => "normal",
                    "title" => "http:BL Blocked Hosts",
                    "description" => "Visitors blocked via Project Honeypot",
                    "weight" => "0",
                    "name" => "management",
                    "context" => 0,
                    "context_only_inline" => 0,
                ],
            ],
        ],
    ],
  ];

  $config = config('views.view.httpbl_blocked_hosts');
  if ($config->isNew()) {
    $config->setData($view_config);
    $config->save();
  }

}
